export const TWIM_TAGS = [
  'Jhana',
  'First jhana',
  'Second jhana',
  'Third jhana',
  'Fourth jhana',
  'Cessation',
  'Nirodha',
  'Majjhima Nikaya',
  'Digha Nikaya',
  'Samyutta Nikaya',
  'Anguttara Nikaya',
  'Pali',
  'Metta',
  'Tanha',
  'Craving',
  'Four noble truths',
  'First noble truth',
  'Second noble truth',
  'Third noble truth',
  'Fourth noble truth',
  'Duḥkha',
  'Meditation object',
  'Object of meditation',
  'Spiritual friend',
  'Directions',
  'Compassion',
  'Karuna',
  'Equanimity',
  'Nirvana',
  'Nibbana',
  'Sotapanna',
  'Awakening',
  'Path',
  'Fruit',
  'Fruit and path',
  'path and fruit',
  '4 noble truths',
  'Arhat',
  'Arahat',
  'Anagami',
  'Sakadagami',
  'Noble silence',
  'Equanimity',
];
